{
    "affected": [
        {
            "package": {
                "ecosystem": "Alpaquita:23",
                "name": "py3-urllib3",
                "purl": "pkg:apk/alpaquita/py3-urllib3?arch=source&distro=23"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "1.26.12-r1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Alpaquita:stream",
                "name": "py3-urllib3",
                "purl": "pkg:apk/alpaquita/py3-urllib3?arch=source&distro=stream"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "1.26.12-r1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "CVE-2025-50182",
    "modified": "2025-06-25T10:12:27.217715Z",
    "published": "2025-06-19T05:59:59.536347Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://docs.bell-sw.com/security/cves/CVE-2025-50182"
        }
    ],
    "schema_version": "1.6.7",
    "severity": [
        {
            "score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "type": "CVSS_V3"
        }
    ]
}
