{
    "affected": [
        {
            "package": {
                "ecosystem": "Alpaquita:23",
                "name": "py3-h2",
                "purl": "pkg:apk/alpaquita/py3-h2?arch=source&distro=23"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "4.1.0-r1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Alpaquita:stream",
                "name": "py3-h2",
                "purl": "pkg:apk/alpaquita/py3-h2?arch=source&distro=stream"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "4.1.0-r0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "BELL-CVE-2025-57804",
    "modified": "2025-09-02T08:57:08.980205Z",
    "published": "2025-08-28T06:11:56.762366Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://docs.bell-sw.com/security/cves/CVE-2025-57804"
        }
    ],
    "schema_version": "1.6.7",
    "upstream": [
        "CVE-2025-57804"
    ]
}
